### ISSUE TITLE
[fe/update]router 설정

### ISSUE THREAD

**Issue by MinKonKim** [B02-group-project/Newsfeed#11]
## To-Do
- [x] react-router-dom 다운
- [x] router 폴더 생성 후 routes.js 파일 만들기
- [x] app.jsx 에서 router 실행하는 코드 넣기

### 기타 알려야 하는 상황을 적어주세요

**### "npm i" or "yarn add "사용해서 "node_modules"업데이트 해주세요!!!**
const router = createBrowserRouter([
  {
    path: "/",   // 경로
    element: <HomePage />, // 실행될 컴포넌트 
  },
  {
    path: "/record/:recordId",
    element: <DetailPage />,
  },
]);

라우터 추가시 주의사항!!!!   
-  path 이름은 팀원들과 합의하에 작성합니다.
-  element는 pages 폴더 내에 있는 컴포넌트만! 넣어야합니다.
### 작업이 완료 예정인 시점을 적어주세요
 2024.06.02

**Comment by tpring** [comment]
얼릉해주세요 현기증 난다말이에요
