### ISSUE TITLE
[fe/update] supabase api 연동하기 / 버튼 사용법 / 모달 사용법

### ISSUE THREAD

**Issue by MinKonKim** [B02-group-project/Newsfeed#13]
## To-Do
- [ ]  api 폴더 생성 후,  supabse.api.js 파일 생성하기
- [ ]  api 연결로직 작성후, 연동 되는지 확인하기
- [ ]  임시로 Sign In 페이지 만들어서 테스트까지 해보기

## ETC

###components/commons/Button.jsx 사용법!!!
```
<Button text={/*버튼에 들어갈 글자(문자열)*/}  handleClick={/*버튼을 눌렀을 때 실행되는 함수*/}  width={/* 원하는 넓이 값 문자열로 */} height={/* 원하는 넓이 값 문자열로 */} fontSize={/* 원하는 넓이 값 문자열로 */}   />
```
fontsize 으로 사용하니 경고문이 나와서 fontSize로 

Modal 사용법
1.    선언한다.
```
  const modal = useModal();
```
2.  버튼 클릭할때 실행할 함수  
```
  const handleClickButton = () => {
    modal.open({ title: "제목", content: "콘텐츠"});  // 객체 생성
  };
```
3.    버튼에 연결
```
    <Button text={"회원가입"} handleClick={handleClickButton} />
```
---------------------------------------------------------------------------
