### ISSUE TITLE
[fe/style] 메인페이지 style작업 / 로그 사용법

### ISSUE THREAD

**Issue by tpring** [B02-group-project/Newsfeed#14]
## To-Do
- [x] 게시글 style 구성
- [x] 사이드 바 style 구성
- [x] 헤더 style 구성
- [x] 로고 교체

## ETC

로그 사용법
```
<Log  width={/* 원하는 넓이 값 문자열로 */} height={/* 원하는 넓이 값 문자열로 */}   logClick={/*버튼을 눌렀을 때 실행되는 함수*/}  />
```
