### ISSUE TITLE
[fe/update] 회원가입 / 로그인 기능 

### ISSUE THREAD

**Issue by MinKonKim** [B02-group-project/Newsfeed#18]
## To-Do
- [x] 회원가입시, userinfo 테이블에 값이 잘 저장되는지 확인
- [x] 로그인시 , 메인페이지로 redirect 되는거 확인하기
- [x] 로그인이 잘 되어 있는지 session 확인하기
- [x] 로그인한 유저의 정보를 잘 받아오는지 확인하기
