### ISSUE TITLE
[fe/update] 게시글 db 연동

### ISSUE THREAD

**Issue by tpring** [B02-group-project/Newsfeed#31]
## To-Do
- [x] 게시일, 사진, 내용,좋아요 db 받아오기
- [x] 케러셀 만들기
- [x] 삭제하기 버튼과 db 연동해서 삭제하기
- [x] 수정버큰 누르면 수정 페이지 이동
- [x] 메인페이지에 id에 맞는 게시글 올라오기
