### ISSUE TITLE
[fe/update] 게시물 작성 및 수정 페이지

### ISSUE THREAD

**Issue by SecretCandy** [B02-group-project/Newsfeed#37]
## Description
- 게시물과 사진에 대한 정보를 받아오지 못했을 때 오류 메세지 띄우도록 변경함
- Delete 기능 추가함

## To-Do
- [x]  CRUD 중 CU 기능 구현
- [x]  CRUD 중 D 기능 구현
- [ ]  Main페이지로 가는 버튼 구현
- [x] 수정 버튼 누르면 supabase와 연동되도록 
- [x] 공유 버튼 누르면 supabase와 연동되도록
- [x] 삭제 기능 없애기
- [ ] button기능 구현해둔거 button component에 있는걸로 변경
- [ ] css 규격에 맞게 수정
- [x] db에 있는 내용 postId를 통해서 수정페이지에 가져오기
- [x] user_id (uuid)도 들어가게
- [x] 이미지 storage에 연동
- [x] image url 받아왔는데 src값으로 화면에 안뜸.. 이거 해결하기
