### ISSUE TITLE
[fe/update] 로그인 연동 확인 여부

### ISSUE THREAD

**Issue by MinKonKim** [B02-group-project/Newsfeed#38]
## To-Do
- [x] 로그인 하고 나서 유저의 id값이 잘 저장되고 불러오게 되는지 확인
- [x] 고유 닉네임 유효성 검사 넣기
- [x] 이미지 저장될 수 있도록 변경하기
- [x] DB에 저장되는 문자열 형식 변경해 보기(부수적인 요소)

### 기타 알려야 하는 상황을 적어주세요
git pull 완벽하게 되시면,
Root 디렉토리 가셔서, 터미널 여시고
```
npm i 
```
입력해주세요~
